== Глоссарий

**Критерии приемки**::
Список минимальных требований, которые услуга или компонент услуги должны выполнить, чтобы быть приемлемыми для ключевых заинтересованных сторон.

**Agile**:;
Общий термин для набора фреймворков и техник, которые вместе позволяют командам и отдельным лицам работать способом, который характеризуется сотрудничеством, определением приоритетов, итерационной и инкрементальной поставкой и таймбоксингом. Существует несколько конкретных методов (или фреймворков), которые классифицируются как Agile, такие как Scrum, Lean и Kanban.

**Практика управления архитектурой**::
Практика предоставления понимания всех различных элементов, составляющих организацию, и того, как эти элементы соотносятся друг с другом.

**Реестр активов**::
База данных или список активов, фиксирующих ключевые атрибуты, такие как право собственности и финансовая стоимость.

**Доступность**::
Способность ИТ-услуги или другого элемента конфигурации выполнять свои согласованные функции при необходимости.

**Практика управления доступностью**::
Практика обеспечения того, чтобы услуги предоставляли согласованные уровни доступности для удовлетворения потребностей клиентов и пользователей.

**Базовый уровень**::
Отчет или метрика, которая служит отправной точкой, по которой можно оценить прогресс или изменение.

**Передовая практика**::
Способ работы, который был доказан как успешный несколькими организациями.

**Большие данные**::
Использование очень больших объемов структурированных и неструктурированных данных из различных источников для получения новых сведений.

**Практика бизнес-анализа**::
Практика анализа бизнеса или некоторого элемента бизнеса, определения его потребностей и рекомендации решений для удовлетворения этих потребностей и/или решения бизнес-проблемы и создания ценности для заинтересованных сторон.

**Бизнес-обоснование**::
Обоснование расходования организационных ресурсов, предоставляющее информацию о затратах, преимуществах, вариантах, рисках и проблемах.

**Анализ воздействия на бизнес (BIA)**::
Ключевое мероприятие в практике управления непрерывностью услуг, которое идентифицирует жизненно важные бизнес-функции и их зависимости.

**Менеджер по бизнес-взаимоотношениям (BRM)**::
Роль, ответственная за поддержание хороших отношений с одним или несколькими клиентами.

**Звонок**::
Взаимодействие (например, телефонный звонок) со службой поддержки. Звонок может привести к регистрации инцидента или запроса на обслуживание.

**Колл-центр/контакт-центр**::
Организация или бизнес-единица, которая обрабатывает большое количество входящих и исходящих звонков и других взаимодействий.

**Способность**::
Возможность организации, человека, процесса, приложения, элемента конфигурации или ИТ-услуги выполнять деятельность.

**Практика управления емкостью и производительностью**::
Практика обеспечения того, чтобы услуги достигали согласованных и ожидаемых уровней производительности, удовлетворяя текущий и будущий спрос экономически эффективным способом.

**Планирование емкости**::
Мероприятие по созданию плана, который управляет ресурсами для удовлетворения спроса на услуги.

**Изменение**::
Добавление, модификация или удаление чего-либо, что может иметь прямое или косвенное влияние на услуги.

**Уполномоченный по изменениям**::
Лицо или группа, ответственная за утверждение изменения.

**Практика контроля изменений**::
Практика обеспечения надлежащей оценки рисков, утверждения изменений для продолжения и управления расписанием изменений с целью максимизации количества успешных изменений услуг и продуктов.

**Модель изменения**::
Повторяемый подход к управлению конкретным типом изменения.

**Расписание изменений**::
Календарь, показывающий запланированные и исторические изменения.

**Тарификация**::
Мероприятие, которое назначает цену за услуги.

**Облачные вычисления**::
Модель для обеспечения доступа по требованию к общему пулу настраиваемых вычислительных ресурсов, которые могут быть быстро предоставлены с минимальными усилиями по управлению или взаимодействием с поставщиком.

**Соответствие**::
Акт обеспечения следования стандарту или набору руководств, или использования правильных, последовательных бухгалтерских или других практик.

**Конфиденциальность**::
Цель безопасности, которая обеспечивает, чтобы информация не становилась доступной или не раскрывалась неуполномоченным лицам.

**Конфигурация**::
Расположение элементов конфигурации (CI) или других ресурсов, которые работают вместе для предоставления продукта или услуги. Также может использоваться для описания настроек параметров для одного или нескольких CI.

**Элемент конфигурации (CI)**::
Любой компонент, которым необходимо управлять для предоставления ИТ-услуги.

**База данных управления конфигурациями (CMDB)**::
База данных, используемая для хранения записей конфигурации на протяжении всего их жизненного цикла. CMDB также поддерживает отношения между записями конфигурации.

**Система управления конфигурациями (CMS)**::
Набор инструментов, данных и информации, который используется для поддержки управления конфигурацией услуг.

**Запись конфигурации**::
Запись, содержащая детали элемента конфигурации (CI). Каждая запись конфигурации документирует жизненный цикл одного CI. Записи конфигурации хранятся в базе данных управления конфигурациями.

**Практика непрерывного улучшения**::
Практика согласования практик и услуг организации с меняющимися бизнес-потребностями посредством постоянного выявления и улучшения всех элементов, участвующих в эффективном управлении продуктами и услугами.

**Непрерывное развертывание**::
Интегрированный набор практик и инструментов, используемых для развертывания изменений программного обеспечения в производственную среду. Эти изменения программного обеспечения уже прошли предопределенные автоматизированные тесты.

**Непрерывная интеграция/непрерывная поставка**::
Интегрированный набор практик и инструментов, используемых для слияния кода разработчиков, сборки и тестирования полученного программного обеспечения и его упаковки так, чтобы оно было готово к развертыванию.

**Контроль**::
Средство управления риском, обеспечения достижения бизнес-цели или следования процессу.

**Затраты**::
Сумма денег, потраченная на конкретную деятельность или ресурс.

**Центр затрат**::
Бизнес-единица или проект, которым назначаются затраты.

**Критический фактор успеха (CSF)**::
Необходимое предварительное условие для достижения намеченных результатов.

**Культура**::
Набор ценностей, разделяемых группой людей, включая ожидания относительно того, как люди должны себя вести, идеи, убеждения и практики.

**Клиент**::
Лицо, которое определяет требования к услуге и берет на себя ответственность за результаты потребления услуги.

**Клиентский опыт (CX)**::
Сумма функциональных и эмоциональных взаимодействий с услугой и поставщиком услуг, воспринимаемых потребителем услуг.

**Панель мониторинга (Dashboard)**::
Графическое представление данных в реальном времени.

**Поставлять и поддерживать**::
Действие цепочки создания ценности, которое обеспечивает предоставление и поддержку услуг в соответствии с согласованными спецификациями и ожиданиями заинтересованных сторон.

**Спрос**::
Вход в систему создания ценности услуг, основанный на возможностях и потребностях внутренних и внешних заинтересованных сторон.

**Развертывание**::
Перемещение любого компонента услуги в любую среду.

**Практика управления развертыванием**::
Практика перемещения нового или измененного аппаратного обеспечения, программного обеспечения, документации, процессов или любого другого компонента услуги в рабочие среды.

**Проектировать и переходить**::
Действие цепочки создания ценности, которое обеспечивает постоянное соответствие продуктов и услуг ожиданиям заинтересованных сторон в отношении качества, затрат и времени выхода на рынок.

**Дизайн-мышление**::
Практичный и ориентированный на человека подход, используемый дизайнерами продуктов и услуг для решения сложных проблем и нахождения практичных и творческих решений, которые удовлетворяют потребностям организации и ее клиентов.

**Среда разработки**::
Среда, используемая для создания или модификации ИТ-услуг или приложений.

**DevOps**::
Организационная культура, направленная на улучшение потока ценности к клиентам. DevOps фокусируется на культуре, автоматизации, Lean, измерении и обмене (CALMS).

**Цифровая трансформация**::
Эволюция традиционных бизнес-моделей для удовлетворения потребностей высоко-авторизованных клиентов, причем технологии играют роль средства.

**Катастрофа**::
Внезапное незапланированное событие, которое наносит большой ущерб или серьезные потери организации. Катастрофа приводит к тому, что организация не может выполнять критически важные бизнес-функции в течение некоторого заранее определенного минимального периода времени.

**Планы восстановления после катастроф**::
Набор четко определенных планов, связанных с тем, как организация будет восстанавливаться после катастрофы, а также возвращаться к состоянию до катастрофы, с учетом четырех измерений управления услугами.

**Драйвер**::
Что-то, что влияет на стратегию, цели или требования.

**Результативность**::
Мера того, достигнуты ли цели практики, услуги или деятельности.

**Эффективность**::
Мера того, использовано ли правильное количество ресурсов практикой, услугой или деятельностью.

**Экстренное изменение**::
Изменение, которое должно быть внедрено как можно скорее.

**Взаимодействовать**::
Действие цепочки создания ценности, которое обеспечивает хорошее понимание потребностей заинтересованных сторон, прозрачность, постоянное взаимодействие и хорошие отношения со всеми заинтересованными сторонами.

**Среда**::
Подмножество ИТ-инфраструктуры, которое используется для определенной цели, например, рабочая среда или тестовая среда. Также может означать внешние условия, которые влияют или воздействуют на что-либо.

**Ошибка**::
Недостаток или уязвимость, которые могут вызывать инциденты.

**Контроль ошибок**::
Мероприятия управления проблемами, используемые для управления известными ошибками.

**Эскалация**::
Акт распространения осведомленности или передачи владения проблемой или рабочим элементом.

**Событие**::
Любое изменение состояния, имеющее значение для управления услугой или другим элементом конфигурации.

**Внешний клиент**::
Клиент, который работает в организации, отличной от поставщика услуг.

**Сбой**::
Потеря способности работать в соответствии со спецификацией или предоставлять требуемый выход или результат.

**Петля обратной связи**::
Техника, при которой выходы одной части системы используются в качестве входов для той же части системы.

**Четыре измерения управления услугами**::
Четыре перспективы, которые критически важны для эффективного и результативного обеспечения ценности для клиентов и других заинтересованных сторон в форме продуктов и услуг.

**Товары**::
Материальные ресурсы, которые передаются или доступны для передачи от поставщика услуг потребителю услуг, вместе с правом собственности и связанными правами и обязанностями.

**Управление**::
Средства, с помощью которых организация направляется и контролируется.

**Идентификатор**::
Уникальное имя, которое используется для идентификации и предоставления прав доступа к системе пользователю, лицу или роли.

**Улучшать**::
Действие цепочки создания ценности, которое обеспечивает непрерывное улучшение продуктов, услуг и практик во всех действиях цепочки создания ценности и четырех измерениях управления услугами.

**Инцидент**::
Незапланированное прерывание услуги или снижение качества услуги.

**Управление инцидентами**::
Практика минимизации негативного воздействия инцидентов путем восстановления нормальной работы услуги как можно быстрее.

**Информация и технологии**::
Одно из четырех измерений управления услугами. Оно включает информацию и знания, используемые для предоставления услуг, а также информацию и технологии, используемые для управления всеми аспектами системы создания ценности услуг.

**Практика управления информационной безопасностью**::
Практика защиты организации путем понимания и управления рисками для конфиденциальности, целостности и доступности информации.

**Политика информационной безопасности**::
Политика, которая регулирует подход организации к управлению информационной безопасностью.

**Практика управления инфраструктурой и платформами**::
Практика надзора за инфраструктурой и платформами, используемыми организацией. Это позволяет осуществлять мониторинг технологических решений, доступных организации, включая решения от третьих сторон.

**Целостность**::
Цель безопасности, которая обеспечивает, чтобы информация изменялась только уполномоченным персоналом и действиями.

**Внутренний клиент**::
Клиент, который работает в той же организации, что и поставщик услуг.

**Интернет вещей**::
Взаимосвязь устройств через интернет, которые традиционно не считались ИТ-активами, но теперь включают встроенные вычислительные возможности и сетевое подключение.

**ИТ-актив**::
Любой финансово ценный компонент, который может способствовать предоставлению ИТ-продукта или услуги.

**Практика управления ИТ-активами**::
Практика планирования и управления полным жизненным циклом всех ИТ-активов.

**ИТ-инфраструктура**::
Все аппаратное обеспечение, программное обеспечение, сети и объекты, которые требуются для разработки, тестирования, предоставления, мониторинга, управления и поддержки ИТ-услуг.

**ИТ-услуга**::
Услуга, основанная на использовании информационных технологий.

**ITIL**::
Руководство по передовой практике для управления ИТ-услугами.

**Руководящие принципы ITIL**::
Рекомендации, которые могут направлять организацию во всех обстоятельствах, независимо от изменений в ее целях, стратегиях, типе работы или структуре управления.

**Цепочка создания ценности услуг ITIL**::
Операционная модель для поставщиков услуг, которая охватывает все ключевые действия, необходимые для эффективного управления продуктами и услугами.

**Kanban**::
Метод визуализации работы, выявления потенциальных блокировок и конфликтов ресурсов и управления незавершенной работой.

**Ключевой показатель эффективности (KPI)**::
Важная метрика, используемая для оценки успеха в достижении цели.

**Практика управления знаниями**::
Практика поддержания и улучшения эффективного, результативного и удобного использования информации и знаний во всей организации.

**Известная ошибка**::
Проблема, которая была проанализирована, но не решена.

**Lean**::
Подход, который фокусируется на улучшении рабочих процессов путем максимизации ценности за счет устранения потерь.

**Жизненный цикл**::
Полный набор стадий, переходов и связанных статусов в жизни услуги, продукта, практики или другой сущности.

**Рабочий (Live)**::
Относится к услуге или другому элементу конфигурации, работающему в рабочей среде.

**Рабочая среда (Live environment)**::
Контролируемая среда, используемая при предоставлении ИТ-услуг потребителям услуг.

**Ремонтопригодность**::
Легкость, с которой услуга или другая сущность может быть отремонтирована или модифицирована.

**Крупный инцидент**::
Инцидент с существенным влиянием на бизнес, требующий немедленного скоординированного разрешения.

**Система менеджмента**::
Взаимосвязанные или взаимодействующие элементы, которые устанавливают политику и цели и обеспечивают достижение этих целей.

**Зрелость**::
Мера надежности, эффективности и результативности организации, практики или процесса.

**Среднее время наработки на отказ (MTBF)**::
Метрика того, как часто услуга или другой элемент конфигурации выходит из строя.

**Среднее время восстановления услуги (MTRS)**::
Метрика того, как быстро услуга восстанавливается после сбоя.

**Измерение и отчетность**::
Практика поддержки принятия правильных решений и непрерывного улучшения путем снижения уровней неопределенности.

**Метрика**::
Измерение или расчет, которые отслеживаются или сообщаются для управления и улучшения.

**Минимально жизнеспособный продукт (MVP)**::
Продукт с достаточным количеством функций для удовлетворения ранних клиентов и предоставления обратной связи для будущей разработки продукта.

**Миссия**::
Краткое, но полное описание общей цели и намерений организации. В нем говорится, что должно быть достигнуто, но не как это должно быть сделано.

**Модель**::
Представление системы, практики, процесса, услуги или другой сущности, которое используется для понимания и прогнозирования ее поведения и отношений.

**Моделирование**::
Деятельность по созданию, поддержанию и использованию моделей.

**Мониторинг**::
Повторное наблюдение за системой, практикой, процессом, услугой или другой сущностью для обнаружения событий и обеспечения знания текущего статуса.

**Практика мониторинга и управления событиями**::
Практика систематического наблюдения за услугами и компонентами услуг, а также записи и сообщения о выбранных изменениях состояния, определенных как события.

**Получать/создавать**::
Действие цепочки создания ценности, которое обеспечивает доступность компонентов услуг тогда и там, где они необходимы, и что они соответствуют согласованным спецификациям.

**Эксплуатация**::
Рутинное выполнение и управление деятельностью, продуктом, услугой или другим элементом конфигурации.

**Операционные технологии**::
Аппаратные и программные решения, которые обнаруживают или вызывают изменения в физических процессах посредством прямого мониторинга и/или управления физическими устройствами, такими как клапаны, насосы и т.д.

**Организация**::
Лицо или группа лиц, которые имеют свои собственные функции с обязанностями, полномочиями и отношениями для достижения своих целей.

**Практика управления организационными изменениями**::
Практика обеспечения того, чтобы изменения в организации были плавно и успешно реализованы и чтобы были достигнуты долгосрочные преимущества путем управления человеческими аспектами изменений.

**Организационная устойчивость**::
Способность организации предвидеть, готовиться, реагировать и адаптироваться к незапланированным внешним влияниям.

**Организационная скорость**::
Скорость, эффективность и результативность, с которыми организация работает. Организационная скорость влияет на время выхода на рынок, качество, безопасность, затраты и риски.

**Организации и люди**::
Одно из четырех измерений управления услугами. Оно обеспечивает, чтобы способ структурирования и управления организацией, а также ее роли, обязанности и системы полномочий и коммуникации были четко определены и поддерживали ее общую стратегию и операционную модель.

**Результат**::
Результат для заинтересованной стороны, обеспечиваемый одним или несколькими выходами.

**Выход**::
Материальный или нематериальный результат деятельности.

**Аутсорсинг**::
Процесс привлечения внешних поставщиков для предоставления продуктов и услуг, которые ранее предоставлялись внутренне.

**Партнеры и поставщики**::
Одно из четырех измерений управления услугами. Оно охватывает отношения, которые организация имеет с другими организациями, участвующими в проектировании, разработке, развертывании, предоставлении, поддержке и/или непрерывном улучшении услуг.

**Партнерство**::
Отношения между двумя организациями, которые предполагают тесное сотрудничество для достижения общих целей и задач.

**Производительность**::
Мера того, что достигнуто или предоставлено системой, человеком, командой, практикой или услугой.

**Пилотное внедрение**::
Тестовая реализация услуги с ограниченной областью в рабочей среде.

**Планировать**::
Действие цепочки создания ценности, которое обеспечивает общее понимание видения, текущего статуса и направления улучшений для всех четырех измерений и всех продуктов и услуг в организации.

**Политика**::
Формально документированные ожидания и намерения руководства, используемые для направления решений и деятельности.

**Практика управления портфелем**::
Практика обеспечения того, чтобы организация имела правильное сочетание программ, проектов, продуктов и услуг для выполнения своей стратегии в рамках ее финансовых и ресурсных ограничений.

**Пост-внедренческий обзор (PIR)**::
Обзор после внедрения изменения для оценки успеха и выявления возможностей для улучшения.

**Практика**::
Набор организационных ресурсов, предназначенных для выполнения работы или достижения цели.

**Проблема**::
Причина или потенциальная причина одного или нескольких инцидентов.

**Практика управления проблемами**::
Практика снижения вероятности и воздействия инцидентов путем выявления фактических и потенциальных причин инцидентов и управления обходными путями и известными ошибками.

**Процедура**::
Документированный способ выполнения деятельности или процесса.

**Процесс**::
Набор взаимосвязанных или взаимодействующих видов деятельности, которые преобразуют входы в выходы. Процесс принимает один или несколько определенных входов и превращает их в определенные выходы. Процессы определяют последовательность действий и их зависимости.

**Продукт**::
Конфигурация ресурсов организации, предназначенная для предложения ценности потребителю.

**Производственная среда**::
См. рабочая среда.

**Программа**::
Набор связанных проектов и мероприятий, а также организационная структура, созданная для руководства и контроля над ними.

**Проект**::
Временная структура, которая создается с целью предоставления одного или нескольких выходов (или продуктов) в соответствии с согласованным бизнес-обоснованием.

**Практика управления проектами**::
Практика обеспечения успешной поставки всех проектов организации.

**Быстрая победа**::
Улучшение, которое, как ожидается, обеспечит окупаемость инвестиций в короткий период времени с относительно небольшими затратами и усилиями.

**Запись**::
Документ, констатирующий достигнутые результаты и предоставляющий свидетельства о выполненных мероприятиях.

**Восстановление**::
Мероприятие по возвращению элемента конфигурации к нормальной работе после сбоя.

**Целевая точка восстановления (RPO)**::
Точка, до которой информация, используемая деятельностью, должна быть восстановлена, чтобы деятельность могла функционировать при возобновлении.

**Целевое время восстановления (RTO)**::
Максимально приемлемый период времени после нарушения услуги, который может пройти, прежде чем отсутствие бизнес-функциональности серьезно повлияет на организацию.

**Практика управления взаимоотношениями**::
Практика установления и развития связей между организацией и ее заинтересованными сторонами на стратегическом и тактическом уровнях.

**Релиз**::
Версия услуги или другого элемента конфигурации или коллекция элементов конфигурации, которая становится доступной для использования.

**Практика управления релизами**::
Практика предоставления новых и измененных услуг и функций для использования.

**Надежность**::
Способность продукта, услуги или другого элемента конфигурации выполнять свои предназначенные функции в течение указанного периода времени или числа циклов.

**Каталог запросов**::
Представление каталога услуг, предоставляющее детали о запросах на обслуживание для существующих и новых услуг, которое становится доступным для пользователя.

**Запрос на изменение (RFC)**::
Описание предлагаемого изменения, используемое для инициирования контроля изменений.

**Разрешение**::
Действие по решению инцидента или проблемы.

**Ресурс**::
Человек или другая сущность, которая требуется для выполнения деятельности или достижения цели. Ресурсы, используемые организацией, могут принадлежать организации или использоваться в соответствии с соглашением с владельцем ресурса.

**Вывод из эксплуатации**::
Акт окончательного изъятия продукта, услуги или другого элемента конфигурации из использования.

**Риск**::
Возможное событие, которое может причинить вред или убытки, или затруднить достижение целей. Также может быть определен как неопределенность результата и может использоваться в контексте измерения вероятности положительных результатов, а также отрицательных.

**Оценка риска**::
Мероприятие по выявлению, анализу и оценке рисков.

**Практика управления рисками**::
Практика обеспечения того, чтобы организация понимала и эффективно обрабатывала риски.

**Услуга**::
Средство обеспечения совместного создания ценности путем содействия достижению результатов, которых хотят достичь клиенты, без необходимости клиентам управлять конкретными затратами и рисками.

**Сервисное действие**::
Любое действие, необходимое для предоставления выхода услуги пользователю. Сервисные действия могут выполняться ресурсом поставщика услуг, пользователями услуг или совместно.

**Сервисная архитектура**::
Представление всех услуг, предоставляемых организацией. Оно включает взаимодействия между услугами и сервисные модели, которые описывают структуру и динамику каждой услуги.

**Каталог услуг**::
Структурированная информация обо всех услугах и сервисных предложениях поставщика услуг, актуальная для конкретной целевой аудитории.

**Практика управления каталогом услуг**::
Практика предоставления единого источника достоверной информации обо всех услугах и сервисных предложениях и обеспечения ее доступности соответствующей аудитории.

**Практика управления конфигурацией услуг**::
Практика обеспечения доступности точной и надежной информации о конфигурации услуг и элементов конфигурации, которые их поддерживают, тогда и там, где это необходимо.

**Потребление услуг**::
Мероприятия, выполняемые организацией для потребления услуг. Оно включает управление ресурсами потребителя, необходимыми для использования услуги, сервисные действия, выполняемые пользователями, и получение (приобретение) товаров (если требуется).

**Практика управления непрерывностью услуг**::
Практика обеспечения поддержания доступности и производительности услуги на достаточном уровне в случае катастрофы.

**Практика проектирования услуг**::
Практика проектирования продуктов и услуг, которые соответствуют назначению, пригодны для использования и могут предоставляться организацией и ее экосистемой.

**Служба поддержки (Service Desk)**::
Точка коммуникации между поставщиком услуг и всеми его пользователями.

**Практика службы поддержки (Service Desk)**::
Практика фиксации спроса на разрешение инцидентов и запросов на обслуживание.

**Практика управления финансами услуг**::
Практика поддержки стратегий и планов организации по управлению услугами путем обеспечения эффективного использования финансовых ресурсов и инвестиций организации.

**Уровень обслуживания**::
Одна или несколько метрик, определяющих ожидаемое или достигнутое качество услуги.

**Соглашение об уровне обслуживания (SLA)**::
Документированное соглашение между поставщиком услуг и клиентом, которое идентифицирует как требуемые услуги, так и ожидаемый уровень обслуживания.

**Практика управления уровнем обслуживания**::
Практика установления четких, основанных на бизнесе целей для производительности услуг, чтобы предоставление услуги могло быть должным образом оценено, проконтролировано и управляемо в соответствии с этими целями.

**Управление услугами**::
Набор специализированных организационных возможностей для обеспечения ценности для клиентов в форме услуг.

**Сервисное предложение**::
Формальное описание одной или нескольких услуг, разработанное для удовлетворения потребностей целевой группы потребителей. Сервисное предложение может включать товары, доступ к ресурсам и сервисные действия.

**Владелец услуги**::
Роль, которая отвечает за предоставление конкретной услуги.

**Сервисный портфель**::
Полный набор продуктов и услуг, которыми организация управляет на протяжении всего их жизненного цикла.

**Поставщик услуг**::
Роль, выполняемая организацией в сервисных отношениях по предоставлению услуг потребителям.

**Предоставление услуг**::
Мероприятия, выполняемые организацией для предоставления услуг. Оно включает управление ресурсами поставщика, настроенными для предоставления услуги; обеспечение доступа к этим ресурсам для пользователей; выполнение согласованных сервисных действий; управление уровнем обслуживания; и непрерывное улучшение. Оно также может включать поставку товаров.

**Сервисные отношения**::
Сотрудничество между поставщиком услуг и потребителем услуг. Сервисные отношения включают предоставление услуг, потребление услуг и управление сервисными отношениями.

**Управление сервисными отношениями**::
Совместные мероприятия, выполняемые поставщиком услуг и потребителем услуг для обеспечения постоянного совместного создания ценности на основе согласованных и доступных сервисных предложений.

**Запрос на обслуживание**::
Запрос от пользователя или уполномоченного представителя пользователя, который инициирует сервисное действие, согласованное как нормальная часть предоставления услуг.

**Практика управления запросами на обслуживание**::
Практика поддержки согласованного качества услуги путем обработки всех предопределенных, инициированных пользователем запросов на обслуживание эффективным и удобным для пользователя способом.

**Практика валидации и тестирования услуг**::
Практика обеспечения того, чтобы новые или измененные продукты и услуги соответствовали определенным требованиям.

**Система создания ценности услуг (SVS)**::
Модель, представляющая, как все компоненты и мероприятия организации работают вместе для обеспечения создания ценности.

**Практика разработки и управления программным обеспечением**::
Практика обеспечения того, чтобы приложения удовлетворяли потребностям заинтересованных сторон с точки зрения функциональности, надежности, сопровождаемости, соответствия требованиям и возможности аудита.

**Стратегия закупок**::
Мероприятие планирования и получения ресурсов из определенного типа источника, который может быть внутренним или внешним, централизованным или распределенным, и открытым или проприетарным.

**Спецификация**::
Документированное описание свойств продукта, услуги или другого элемента конфигурации.

**Спонсор**::
Лицо, которое авторизует бюджет на потребление услуг. Также может использоваться для описания организации или лица, которое предоставляет финансовую или другую поддержку для инициативы.

**Заинтересованная сторона**::
Лицо или организация, которые имеют интерес или вовлеченность в организацию, продукт, услугу, практику или другую сущность.

**Стандарт**::
Документ, установленный консенсусом и утвержденный признанным органом, который предусматривает общее и повторное использование, обязательные требования, руководящие указания или характеристики для своего предмета.

**Стандартное изменение**::
Низкорисковое, предварительно утвержденное изменение, которое хорошо понято и полностью документировано и которое может быть реализовано без необходимости в дополнительном утверждении.

**Статус**::
Описание конкретных состояний, которые сущность может иметь в данный момент времени.

**Практика управления стратегией**::
Практика формулирования целей организации и принятия курсов действий и распределения ресурсов, необходимых для достижения этих целей.

**Поставщик**::
Заинтересованная сторона, ответственная за предоставление услуг, которые использует организация.

**Практика управления поставщиками**::
Практика обеспечения надлежащего управления поставщиками организации и их уровнями производительности для поддержки предоставления бесперебойных качественных продуктов и услуг.

**Команда поддержки**::
Команда с ответственностью за поддержание нормальных операций, решение запросов пользователей и разрешение инцидентов и проблем, связанных с указанными продуктами, услугами или другими элементами конфигурации.

**Система**::
Комбинация взаимодействующих элементов, организованных и поддерживаемых для достижения одной или нескольких заявленных целей.

**Системное мышление**::
Целостный подход к анализу, который фокусируется на том, как составные части системы работают, взаимосвязаны и взаимодействуют с течением времени и в контексте других систем.

**Технический долг**::
Общий бэклог переделок, накопленный выбором обходных путей вместо системных решений, которые заняли бы больше времени.

**Тестовая среда**::
Контролируемая среда, установленная для тестирования продуктов, услуг и других элементов конфигурации.

**Третья сторона**::
Заинтересованная сторона, внешняя по отношению к организации.

**Пропускная способность**::
Мера объема работы, выполняемой продуктом, услугой или другой системой за заданный период времени.

**Транзакция**::
Единица работы, состоящая из обмена между двумя или более участниками или системами.

**Вариант использования (Use case)**::
Техника, использующая реалистичные практические сценарии для определения функциональных требований и проектирования тестов.

**Пользователь**::
Лицо, которое использует услуги.

**Полезность**::
Функциональность, предлагаемая продуктом или услугой для удовлетворения конкретной потребности. Полезность может быть обобщена как «что делает услуга» и может использоваться для определения, является ли услуга «соответствующей назначению». Чтобы иметь полезность, услуга должна либо поддерживать производительность потребителя, либо устранять ограничения потребителя. Многие услуги делают и то, и другое.

**Требования полезности**::
Функциональные требования, которые были определены клиентом и являются уникальными для конкретного продукта.

**Валидация**::
Подтверждение того, что система, продукт, услуга или другая сущность соответствует согласованной спецификации.

**Ценность**::
Воспринимаемые преимущества, полезность и важность чего-либо.

**Поток создания ценности**::
Серия шагов, которые организация предпринимает для создания и предоставления продуктов и услуг потребителям.

**Потоки создания ценности и процессы**::
Одно из четырех измерений управления услугами. Оно определяет мероприятия, рабочие процессы, средства контроля и процедуры, необходимые для достижения согласованных целей.

**Видение**::
Определенное стремление того, кем организация хотела бы стать в будущем.

**Гарантия**::
Уверенность в том, что продукт или услуга будут соответствовать согласованным требованиям. Гарантия может быть обобщена как «как работает услуга» и может использоваться для определения, является ли услуга «пригодной для использования». Гарантия часто связана с уровнями обслуживания, соответствующими потребностям потребителей услуг. Это может быть основано на формальном соглашении, или это может быть маркетинговое сообщение или имидж бренда. Гарантия обычно касается таких областей, как доступность услуги, ее емкость, уровни безопасности и непрерывности. Говорят, что услуга обеспечивает приемлемую уверенность, или «гарантию», если все определенные и согласованные условия выполнены.

**Требования гарантии**::
Обычно нефункциональные требования, полученные в качестве входных данных от ключевых заинтересованных сторон и других практик.

**Водопадный метод**::
Подход к разработке, который является линейным и последовательным с четкими целями для каждой фазы разработки.

**Рабочая инструкция**::
Подробное описание, которому необходимо следовать для выполнения деятельности.

**Обходной путь**::
Решение, которое уменьшает или устраняет влияние инцидента или проблемы, для которого полное разрешение еще недоступно. Некоторые обходные пути снижают вероятность инцидентов.

**Практика управления персоналом и талантами**::
Практика обеспечения того, чтобы у организации были нужные люди с соответствующими навыками и знаниями и на правильных ролях для поддержки ее бизнес-целей.

(Конец Глоссария)